# Generated by Django 2.2.9 on 2020-09-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='student')),
                ('std', models.IntegerField(max_length=10)),
                ('address', models.TextField(max_length=50)),
                ('mo_number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
