# Generated by Django 2.2.9 on 2020-09-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mo_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.IntegerField(),
        ),
    ]
